import type { EnvEntry } from './EnvParser.js';
import type { Config } from './ConfigLoader.js';

export class CodeGenerator {
	constructor(private config: Config) {}

	generate(entries: EnvEntry[]): string {
		const parts = [
			this.buildHeader(),
			"import { z } from 'zod';",
			'',
			this.buildEnvNames(entries),
			'',
			this.buildSchema(entries),
			'',
			this.buildTypeAlias(),
		];

		if (this.config.generateGetEnvs) {
			parts.push('', this.buildGetEnvs(entries));
		}

		return parts.join('\n') + '\n';
	}

	private buildHeader(): string {
		return '// Auto-generated by env-types-generator — DO NOT EDIT';
	}

	private buildEnvNames(entries: EnvEntry[]): string {
		const keys = entries.map((e) => `'${e.key}'`).join(', ');
		return `export const ENV_NAMES = [${keys}] as const;`;
	}

	private buildSchema(entries: EnvEntry[]): string {
		const lines = entries.map((e) => `  ${e.key}: ${this.entryToZodExpression(e)},`);
		return `export const envSchema = z.object({\n${lines.join('\n')}\n});`;
	}

	private buildTypeAlias(): string {
		return `export type ${this.config.typeName} = z.infer<typeof envSchema>;`;
	}

	private buildGetEnvs(_entries: EnvEntry[]): string {
		const source = this.config.envSource;
		const envAccess = source === 'import.meta.env' ? 'import.meta.env[name]' : 'process.env[name]';

		return [
			`export const getEnvs = (): ${this.config.typeName} => {`,
			`  const raw = Object.fromEntries(`,
			`    ENV_NAMES.map(name => [name, ${envAccess}])`,
			`  );`,
			`  return envSchema.parse(raw);`,
			`};`,
		].join('\n');
	}

	entryToZodExpression(entry: EnvEntry): string {
		if (entry.type === 'boolean') {
			return `z.enum(['true', 'false']).transform(v => v === 'true')`;
		}

		if (entry.type === 'number') {
			return `z.coerce.number()`;
		}

		// string
		if (entry.defaultValue !== undefined) {
			return `z.string().default('${entry.defaultValue}')`;
		}

		if (entry.isOptional) {
			return `z.string().optional()`;
		}

		return `z.string().min(1)`;
	}
}
