// Auto-generated by env-types-generator — DO NOT EDIT
import { z } from 'zod';

export const ENV_NAMES = ['API_URL', 'PUBLIC_CLERK_PUBLISHABLE_KEY', 'CLERK_SECRET_KEY'] as const;

export const envSchema = z.object({
	API_URL: z.string().min(1),
	PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
	CLERK_SECRET_KEY: z.string().min(1),
});

export type EnvironmentVariables = z.infer<typeof envSchema>;

export const getEnvs = (): EnvironmentVariables => {
	const raw = Object.fromEntries(ENV_NAMES.map((name) => [name, import.meta.env[name]]));
	return envSchema.parse(raw);
};
